[package]
name = "homeworkbot"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
frankenstein = { version = "0.30.4", features = ["async-http-client"] }
tokio = { version = "1.36.0", features = ["full"] }
